# Generated by Django 5.0.3 on 2024-04-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
