# Generated by Django 5.0.3 on 2024-04-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
                ('bid_price', models.IntegerField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
