# Generated by Django 5.0.3 on 2024-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bid_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
