# Generated by Django 5.0.3 on 2024-04-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_bid_amount_alter_bid_bid_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bid_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
