# Generated by Django 5.0.3 on 2024-04-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_bid_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='big_listing',
            new_name='bid_listing',
        ),
        migrations.AlterField(
            model_name='listings',
            name='bid_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
