# Generated by Django 5.0.3 on 2024-04-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('Collectables', 'Collectables & Art'), ('Costumes', 'Costumes'), ('Props', 'Props'), ('Figures', 'Figures'), ('Home', 'Home & Decor'), ('Accessories', 'Accessories & More'), ('Games', 'Games & Puzzles'), ('Gift Cards', 'Gift Cards'), ('Clearance', 'Clearance')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
