# Generated by Django 5.0.3 on 2024-04-09 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listings_created_listings_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='in_watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
